# syntax=docker/dockerfile:1.6

FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
# RUN mvn -B -ntp -DskipTests dependency:go-offline
COPY . .
RUN mvn -B -ntp -DskipTests -U package

# ---- runtime stage ----
FROM payara/micro:6.2024.10-jdk17

COPY --from=build /app/target/*.war /opt/payara/deployments/ROOT.war

CMD ["--deploymentDir","/opt/payara/deployments","--noCluster"]

